# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-06-24 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0002_auto_20210624_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='sentdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
